### ISSUE TITLE
Dashboard, media library, upload files:

### ISSUE THREAD

**Issue by WTWtesting** [HTTP3D/WalkTheWeb#6]
Uploaded a Jpeg image, cant see it in the media page unless I tick “show hidden”, then it appears but doesn’t show a thumbnail in the media page:

![image](https://user-images.githubusercontent.com/123270827/213887723-c5b5f7e6-1549-4560-9670-7f19ecabac0c.png)

I click on information (!) under it, and this is what I get:

![image](https://user-images.githubusercontent.com/123270827/213887748-bb09d9aa-12f5-406e-90d6-c201a920d902.png)

If I click on the link I get this:

![image](https://user-images.githubusercontent.com/123270827/213887766-f316b3df-701c-4e24-9594-ab3af4453c30.png)

The image opens normally if I browse it from the server files:

![image](https://user-images.githubusercontent.com/123270827/213887799-c8580b30-02fc-4718-bffa-06638d207ed8.png)

Tried to upload a png image, all the same happens beside, it is shown (broken thumbnail) without ticking the “show hidden files”. Otherwise all the same.

.glb files are not uploading. Nothing happens when you select a file and try to upload. And if I upload a glb into the same file on the server directly (tried to test if it is just an upload script issue), the platform doesnt see it in  “my files”. Which can also be a challenge as many may need to add bulk media files by extracting it directly to the server instead of uploading then one at a time from the dashboard.

* Added building to a community, but now I cant see it from admin dashboard nor if I am browsing as a guest even if in the menu in the footer, it suggest the building is actually there. I wonder it is the same issue like in saving media:

![image](https://user-images.githubusercontent.com/123270827/213887886-d7104f83-12cf-4076-b416-f3021c20f375.png)

** Content folder permission on the server:

![image](https://user-images.githubusercontent.com/123270827/213887914-a6ac6c67-fa94-4895-83cc-6611658a5511.png)

**Comment by adishno** [comment]
With some investigating, we see the files did upload to the server correctly. The image was resized and saved as 3 different sizes as designed. 

So the issue remains that the files are there but cannot be browsed. I think it has to do with the nginx user not in the group that the permissions are set. 

Also note that the nginx user needs to be able to write to the /content folder if you want the WTW Updates process to be able to overwrite the files with the later releases. This /content folder also includes the plugins and related updates. If you choose to only allow the nginx user access to this folder, you may need to download and update the WTW and Plugin files directly; but that is a straight copy over the existing files (replacing them).

Not seeing the building had to do with the Mime Types for .glb, .gltf, .obj, and .babylon. Even though they corrected it on the server level, I have added it to the htaccess file to avoid this issue in the future.  Thanks for all of the feedback! I am working to make it better!
